package surveyTest;

import java.io.Serializable;

//Class for storing responses for any kind of Question
public class Response implements Serializable {

	private static final long serialVersionUID = 4746343343607324482L;
	
	private String response;
	
	public Response(String r) {
		this.response = r;
	}
	
	public void display(AbstractSurveyIO io) {
		io.display(this.response);
	}
	
	//Auto generated by Eclipse
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((response == null) ? 0 : response.hashCode());
		return result;
	}
	
	//Auto generated by Eclipse, for comparing test maker's correct response to a test taker's given response
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Response other = (Response) obj;
		if (response == null) {
			if (other.response != null)
				return false;
		} else if (!response.equals(other.response))
			return false;
		return true;
	}
	
	

}
